### ISSUE TITLE
添加Detect_BIT_OJ升级版

### ISSUE THREAD

**Issue by CJJ-amateur-programmer** [YDX-2147483647/BIT-enhanced#8]
我写了一个Detect_BIT_OJ的升级版，希望也放到这个repository中，方便大家使用。

项目地址：https://github.com/CJJ-amateur-programmer/Detect_BIT_OJ_getchar

**Comment by YDX-2147483647** [comment]
这个仓库[采用 GPL-3.0 许可](https://github.com/YDX-2147483647/BIT-enhanced/blob/main/LICENSE)，比较强。如果你确定采用，欢迎加进来。（我看你仓库里目前没写许可）

另外，从以后更新和推广来看，可能加到 https://github.com/YDX-2147483647/best-of-bits 更好。（也就是这个仓库`README.md`中第一个徽章）原因如下。

- 你可以完全控制自己的脚本，没有这个仓库的限制
- best-of-BITs 会根据你仓库的维护情况打分，自动排序
- 如果你发布到 [Greasy Fork](https://greasyfork.org)，排序也会考虑下载量
- “👩‍🏫教学运行与考务”的东西列在一起，方便大家查

你现在怎么想呢？

**Comment by CJJ-amateur-programmer** [comment]
确定采用；
可以把我的脚本同时导入这个仓库和 best-of-BITs；
Greasy Fork上传老是不成功，可以一起上传。

**Comment by YDX-2147483647** [comment]
好。利用 webhook 可让 Greasy Fork 自动从仓库更新，挂到你原来仓库，还是挂这里？

**Comment by CJJ-amateur-programmer** [comment]
挂你那里吧

**Comment by YDX-2147483647** [comment]
行。我估计这几天再稍微改改（元数据、代码风格等），都弄好后再关这个 issue。

**Comment by CJJ-amateur-programmer** [comment]
关于乐学侧边栏修改，我昨晚写好了升级版，可以通过在弹出窗口中拖动来决定是否显示以及先后顺序。可以也加入进来。
https://github.com/CJJ-amateur-programmer/BIT_lexue_sidebar_optimizer

**Comment by YDX-2147483647** [comment]
已经上传到 Greasy Fork 了。

[BIT-Programming-Detect](https://greasyfork.org/zh-CN/scripts/488587) ![Greasy Fork](https://img.shields.io/greasyfork/v/488587)

能否试一下？因为我现在没有能提交的编程题。

**Comment by CJJ-amateur-programmer** [comment]
经测试，正常检测并下载、断网提示并下载、离开页面提示、错过提交时间提示等功能均正常。

**Comment by YDX-2147483647** [comment]
好，谢谢！

**Comment by CJJ-amateur-programmer** [comment]
经测试，正常检测并下载、断网提示并下载、离开页面提示、错过提交时间提示等功能均正常。
